### PR TITLE
nix: fix package and add devshell

### PR DESCRIPTION
**Pull request by outfoxxed**
Fixes nix package + adds dev environment

### CODE REVIEW

**Comment by outfoxxed** [comment]
@fufexan I preserved the behavior, but generating compile_commands.json from the shell hook seems rather odd.

**Comment by outfoxxed** [comment]
rebased on #8

**Review by fufexan — APPROVED** [review]
LGTM. @vaxerski for the cpp/qml side of things.

**Comment by fufexan** [comment]
> @fufexan I preserved the behavior, but generating compile_commands.json from the shell hook seems rather odd.

I don't assume many people use the devshell anyway, but I wanted to have it automatically done or else clangd would yell at me.

**Comment by vaxerski** [comment]
cpp stuff is based on #8 and discussion is there

**Comment by outfoxxed** [comment]
rebased on #8 again

**Comment by outfoxxed** [comment]
*again

**Comment by outfoxxed** [comment]
how

**Review by fufexan — APPROVED** [review]

**Pull request merged**
