### PR TITLE
core: make the .desktop file use the hwinfo icon

### PR DESCRIPTION
**Pull request by alba4k**
before
immagine

after
immagine

### CODE REVIEW

**Review by vaxerski — APPROVED** [review]

**Comment by vaxerski** [comment]
generally we should make a hypr-icons pack for all the apps.

**Comment by alba4k** [comment]
Also, but using system icons is fine too for such a small utility

**Comment by vaxerski** [comment]
ye I mean in the future as we get more

**Comment by alba4k** [comment]
Sure then ig

**Pull request merged**
