### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Soccera1**
Add footnote explaining compatibility and how to check compatibility with displaying logos

### CODE REVIEW

**Review by vaxerski — APPROVED** [review]

**Comment by HiFIi** [comment]
Woooooo

**Comment by Soccera1** [comment]
> Woooooo

Thanks!

**Comment by alba4k** [comment]
will probably needs some rewording at some point 😅

**Comment by Soccera1** [comment]
The whole thing is temporary while Vax figures out a better solution than relying on a system icon as the only way to get an icon, so I just put up something quickly that is easily understandable. If Vax decides to embed icons, it'll need to be modified anyway, so I don't think it's worth putting a lot of time into this now.

**Pull request merged**
